require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, min_ios_version_supported
prepare_react_native_project!
use_modular_headers!
use_frameworks!

target 'rn_june_2025' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :fabric_enabled => false,
    :hermes_enabled => true,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  pod 'FirebaseAuth'
  pod 'FirebaseCore'
  pod 'FirebaseCoreInternal'
  pod 'GoogleUtilities'

  pod 'RNScreens', :path => '../node_modules/react-native-screens', :modular_headers => true

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
    )
  end
end
